version: '3.0'
services:
  webapp:
    container_name: webapp
    image: onion.clean:v.0.1
    ports:
      - 8080:8080
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      SQLSERVER_CONNECTION_STRING: Server=sqlserver;Database=Ecommerce;User Id=sa;Password=sql@pa22w0rd; TrustServerCertificate=Yes;
    networks:
      - ecommerce
networks:
  ecommerce:
    driver: bridge
    name: ecommerce
    external: true
